import Head from 'next/head'
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Header from './_header'
import ScoreMenu from './_score-menu'
import Footer from './_footer'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Next Learn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Header/>
      <div className='min-h-500'>
        <Component/>
      </div>
      <Footer/>
      <ScoreMenu/>
    </>
  )
}
