import Head from 'next/head'
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Header from './_header'
import ScoreMenu from './_score-menu'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Next Learn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Header/>
      <Component {...pageProps} />
      <ScoreMenu/>
    </>
  )
}
